import '@/styles/globals.css'
import Head from 'next/head'
import MainLayout from './components/MainLayout'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title> Anonymous Notes </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/AN-psg.ico" />
      </Head>
      
      <MainLayout>
        <Component {...pageProps} />
      </MainLayout>
    </>
  );
}
